### ISSUE TITLE
How to disable log

### ISSUE THREAD

**Issue by lucasjinreal** [mochi-mqtt/server#361] opened 2024-01-16 11:33 UTC
How I suddenly found after I enabled badger, the write folder has a v0000.log which is very huge, I don't need log, how to disable it? (purhaps not casued by badger but mochi it self)

**Comment by mochi-co** [comment] 2024-01-21 11:04
Closed as duplicate of #363, sorry for the delay.

**Closed by mochi-co** 2024-01-21 11:04 UTC
