### ISSUE TITLE
Specify properties when inline publishing

### ISSUE THREAD

**Issue by TheCount** [mochi-mqtt/server#430] opened 2024-08-28 11:17 UTC
The [Server.Publish](https://pkg.go.dev/github.com/mochi-mqtt/server/v2#Server.Publish) API does not allow to specify [MQTT 5 properties](https://pkg.go.dev/github.com/mochi-mqtt/server/v2@v2.6.5/packets#Properties).

The obvious workaround would be to use [Server.InjectPacket](https://pkg.go.dev/github.com/mochi-mqtt/server/v2#Server.InjectPacket) instead. However, the server's inline client `Server.inlineClient` is not exported.

Is there a simple way to inject a publishing with properties?

**Comment by thedevop** [comment] 2024-08-28 23:56
Duplicate of #428.

**Closed by thedevop** 2024-08-28 23:56 UTC
